name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/delivery-booking

jobs:
  deploy:
    runs-on: self-hosted # Use the self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Podman command
      run: /Users/WABA/Documents-SSD/Tools/multi-docker-odoo/instances/odoo17dev2/update_odoo.sh

